version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9999:80"
    volumes:
      - '/app:/app:cached'
