# Generated by Django 3.2.5 on 2021-12-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(default=0, max_length=1, verbose_name='勉強部屋'),
            preserve_default=False,
        ),
    ]
