# Generated by Django 3.2.5 on 2021-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.IntegerField(default=1, verbose_name='勉強部屋'),
        ),
    ]
