# Generated by Django 3.2.5 on 2022-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.CharField(default='', max_length=37, verbose_name='Discordユーザ名'),
        ),
    ]
