# Generated by Django 3.2.5 on 2022-01-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='participants',
            new_name='creator',
        ),
    ]
