# Generated by Django 3.2.5 on 2022-01-07 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220107_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_name', models.CharField(default='', max_length=37, validators=[django.core.validators.RegexValidator(message='name#0000の形式で入力してください', regex='^.{3,32}#[0-9]{4}$')], verbose_name='Discordユーザ名')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='participants',
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(related_name='participants', to='app.Discord_User')),
            ],
        ),
    ]
