# Generated by Django 3.2.5 on 2022-01-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220107_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_user',
            name='creator_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.schedule'),
        ),
    ]
