# Generated by Django 3.2.5 on 2022-01-08 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_discord_user_creator_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord_user',
            name='creator_of',
        ),
        migrations.AddField(
            model_name='schedule',
            name='creator',
            field=models.CharField(default='', max_length=37, validators=[django.core.validators.RegexValidator(message='name#0000の形式で入力してください', regex='^.{3,32}#[0-9]{4}$')], verbose_name='Discordユーザ名'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(to='app.Discord_User'),
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
