# Generated by Django 3.2.5 on 2022-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220108_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='app.Discord_User'),
        ),
    ]
